const translations = {
    en: {
        navServices: "Services",
        navNews: "News",
        navJoinUs: "Join us",
        navContact: "Contact",
        caption1: "Riyadh City Towers, Saudi Arabia",
        caption2: "Al-Ittihad Stadium, Saudi Arabia",
        caption3: "Al Faisaliah Tower, Saudi Arabia",
        servicesTitle: "Services",
        learnMore: "Learn more",
        architecture: "Architecture",
        masterPlanning: "Master planning",
        landscape: "Landscape",
        structure: "Structure",
        siteSupervision: "Site supervision",
        interiorDesign: "Interior Design",
        newsTitle: "News",
        newsProjectTitle:"“Construction Technology Award 2025 – BIM Project of The Year”",
        projectDetails: "More details",
        projectText: "MIMAR Group has been awarded the Innovation in Design Award at the Design Middle East Awards for our Dhahran Expo Convention Center project. This recognition celebrates our commitment to pushing boundaries and redefining architectural excellence.",
        partenersTitle:"Our Success Parteners",
        joinUsTitle: "Join Us",
        joinUsText1: "Be part of a dynamic team shaping the future.",
        joinUsText2: "Grow your skills and make an impact with us.",
        joinUsButton: "Join Us",
        locations:  "📍 Reiad, KSA",
        contactTitle: "Let's work together",
        phone: "Phone",
        location: "Location",
        email: "E-mail",
        followUs: "Follow us",
        copyright: "© 2025 ENGIBRAHEMOMARA. All rights reserved."
    },
    ar: {
        navServices: "الخدمات",
        navNews: "الأخبار",
        navJoinUs: "انضم إلينا",
        navContact: "تواصل معنا",
        caption1: "ابراج مدينه الرياض ، السعوديه",
        caption2: "ملعب الاتحاد، السعودية",
        caption3: "برج الفيصليه ، السعودية",
        servicesTitle: "الخدمات",
        learnMore: "اعرف المزيد",
        architecture: "العمارة",
        masterPlanning: "المخطط العام",
        landscape: "تصميم المناظر الطبيعية",
        structure: "الهيكل الإنشائي",
        siteSupervision: "الإشراف على المواقع",
        interiorDesign: "التصميم الداخلي",
        newsTitle: "الأخبار",
        newsProjectTitle:"“جائزة تكنولوجيا البناء 2025 – مشروع BIM لهذا العام”",
        projectDetails: "تفاصيل أكثر",
        projectText: "حصلت مجموعة ميمار على جائزة الابتكار في التصميم في جوائز الشرق الأوسط للتصميم عن مشروع مركز معارض الظهران. هذا التكريم يعكس التزامنا بدفع الحدود وإعادة تعريف التميز المعماري.",
        partenersTitle:"شركاء النجاح ...",
        joinUsTitle: "انضم إلينا",
        joinUsText1: "كن جزءًا من فريق ديناميكي يشكل المستقبل.",
        joinUsText2: "نمّي مهاراتك واصنع تأثيرًا معنا.",
        joinUsButton: "انضم الآن",
        locations:  "📍 الرياض، السعودية",
        contactTitle: "دعنا نعمل معًا",
        phone: "الهاتف",
        location: "موقعنا",
        email: "البريد الإلكتروني",
        followUs: "تابعنا",
        copyright: "© 2025 ENGIBRAHEMOMARA. جميع الحقوق محفوظة."
    }
};
